server:
  http:
    addr: "${HTTPADDR:0.0.0.0:8000}"
    timeout: 1s
    pathprefix: "/api/authz"
  grpc:
    addr: "${GRPCADDR:0.0.0.0:9000}"
    timeout: 1s
  minLogLevel: Info
data:
  spiceDb:
    useTLS: false
    endpoint: "${ENDPOINT:0.0.0.0:50051}"
    token: "${PRESHARED}" # token takes precedence over tokenFile
    tokenFile: "${PRESHARED_FILE:.secrets/local-spicedb-secret}"
